### ISSUE TITLE
Lattice file clean up ("IonZ", "IonQ", and "IonW")

### ISSUE THREAD

**Issue by kryv** [frib-high-level-controls/FLAME#10]
At this point, lattice files (e.g to_strl.lat) include "IonZ", ("IonQ") and "IonW" parameter.
However, these values don't use in the case of we put "IonChargeStates" and "NCharge".
In addition, "IonChargeStates" and "NCharge" already include the role of "IonZ" and "IonQ", and "IonW" is not used in source code.

I think we should remove these parameter from lattice file because it confuses the definition of the reference ion charge state etc.
(First element of "IonChargeStates" is used as a reference for now.)

**Comment by jbengtsson** [comment]
Kei,

I have cleaned up the lattice files and pushed it to the jb branch.

Johan

**Comment by kryv** [comment]
Thank you. I have checked your branch version.
I will close this issue after main repository update.
