### ISSUE TITLE
Folder structure clean-up

### ISSUE THREAD

**Issue by kryv** [frib-high-level-controls/FLAME#12]
For release version of the FLAME, I suggest to folder structure clean-up.
1. Test data folders (e.g. FLAME/src/data and FLAME/python/flame/test) should be put in "one" proper place. (FLAME/src folder should not include data folder)
2. The test script file name FLAME/python/flame/test/test_jb.py is inadequate.

**Comment by jbengtsson** [comment]
Kei,

I have fixed 12.2.

Mike, can you advice on 12.1?

Johan

**Comment by mdavidsaver** [comment]
> 1. Test data folders (e.g. FLAME/src/data and FLAME/python/flame/test) should be put in "one" proper place. (FLAME/src folder should not include data folder)

The consumers of this test data are different.  The python unit tests can be used after installation as flame/test/ is installed (as is the python custom).  The C++ tests are only run at build time as the test executables are not installed.  These C++ tests do not involve python in any way, so it seems odd to place them under python/.  The alternative is to move the data for the python tests out of python/.  This would mean that the source tree and the build/install tree will be different.  Would this be confusing?

Can we agree to ignore this?  The files under src/data/ are used only to validate the glps parser.  No physics is being tested here.
