### ISSUE TITLE
Request to add tests

### ISSUE THREAD

**Issue by kryv** [frib-high-level-controls/FLAME#13]
Could you please add following physics issues to test script?
1. Strict (not simplify) Transit Time factor calculation (e.g. start from lower (or higher) energy than design).
2. Turn on the emittance growth in rf cavities. (This is only implemented in [developing repository](https://github.com/jbengtsson/jmbgsddb) for now.)

**Comment by jbengtsson** [comment]
Kei,

I have added unit tests for Transit Time factors and RF Cavity emittance
growth; and pushed to the jb branch.

Johan

**Comment by kryv** [comment]
Thank you. I will close this issue after main repository update.
