### ISSUE TITLE
Memory leak in GLPSPrinter()

### ISSUE THREAD

**Issue by dylan171** [frib-high-level-controls/FLAME#14]
The following script produces a serious memory leak (about 4MB/sec)

```python
import flame, time, resource

from collections import OrderedDict

with open('to_strl.lat', 'r') as fp:
    lat = flame.GLPSParser().parse(fp)

while True:
    time.sleep(0.5)
    lattice = OrderedDict(lat)
    ### the following lines produce the leak ###
    elements = lattice['elements']
    lattice['elements'] = []
    for e in elements:
        lattice['elements'].append(OrderedDict(e))
    ############################################
    flame.GLPSPrinter(lattice)
    print resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
```

It seems to have something to do with the use of OrderedDict for elements.

**Comment by dylan171** [comment]
With more testing I found that using
```python
lattice['elements'].append(list(e))
```
also produces the leak, so it doesn't seem specifically  related to the use of OrderedDict.

**Comment by mdavidsaver** [comment]
Should be fixed by 7ed33cc39ff7118bd351aee309aeed7944803f53.  Issue was leak of reference returned by PySequence_GetItem() within flame.GLPSPrinter().

**Comment by mdavidsaver** [comment]
FYI, I have a helper for these type of situations.  https://github.com/mdavidsaver/pyDevSup/blob/master/devsupApp/src/devsup/disect.py

```py
from disect import periodic
periodic(30)
```

Collects stats on the number off instances of each type/class and prints a delta of these counts every 30 seconds.  Good for finding slow leaks in long running processes.

**Comment by dylan171** [comment]
That fixed it. Thanks.
