### ISSUE TITLE
ImportError libflame_core.so.0 cannot open shared object file

### ISSUE THREAD

**Issue by crispd** [frib-high-level-controls/FLAME#39]
I'm trying to install flame on a new machine. I went through the steps in the documentation, and even ran the test, everything seemed to run fine. I now see a flame folder in /usr/lib/python3/dist-packages/.

However, when I try to run `import flame` I get the below output. I can't tell if this is due to something I did, is this error familiar? Thanks for any and all help.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-a72649800412> in <module>
      1 import cothread
----> 2 import flame

/usr/lib/python3/dist-packages/flame/__init__.py in <module>
      2 from collections import OrderedDict
      3 
----> 4 from ._internal import (Machine as MachineBase,
      5                         GLPSPrinter, _GLPSParse,
      6                         _pyapi_version, _capi_version,

ImportError: libflame_core.so.0: cannot open shared object file: No such file or directory
```

**Comment by crispd** [comment]
I'm running Python 3.9, and pulled the most recent from this github repo.

**Comment by zhangt58** [comment]
How do you install it? Note that it could be installed via pip, i.e. `pip install flame-code`, probably you may also need to install `libpython3-dev` package on Debian and its derivatives.

**Comment by crispd** [comment]
I first ensured all the pre-requisites were installed.
Then, starting from my home directory, I ran:
```
git clone https://github.com/frib-high-level-controls/FLAME.git flame
mkdir flame/build
cd flame/build
cmake .. -DPYTHON_EXECUTABLE=/usr/bin/python3
make
make test
sudo make install
```
I've just installed libpython3-dev so I'll see if that changes anything.
EDIT: reviewing the output again, it appears that was already installed. I guess I'll try `pip install flame-code`.

**Comment by crispd** [comment]
I'll also add that I actually had to manually build cmake in order for it to work. On most systems I'm able to take cmake for granted, so I don't know how normal it is to have to build it yourself. But `make test` passed, so I'm thinking cmake isn't my problem.

**Comment by crispd** [comment]
Might be neat to have a `make uninstall`. But `pip install flame-code` seemed to work (at least, I'm not getting any errors from `import flame` or `from flame import Machine`)

**Comment by crispd** [comment]
Might be good to add that you can use `pip install flame-code` to the readme + documentation. When you have time to, of course.

**Comment by zhangt58** [comment]
If one only wants to use the code, `pip instal flame-code` is the best way, while for developers, just follow the build guide, I'll update the README.
