### ISSUE TITLE
Bugfix: MpoleLevel in main.cpp

### ISSUE THREAD

**Issue by kryv** [frib-high-level-controls/FLAME#4]
In the case of MpoleLevel (multipoleLevel in TLM) = 1 or 2, we consider dipole elements in a rf cavity.
Here, we use the 7th column (count from 1st = x) of the transfer matrix.
The 7th column is used for only centroid (which define as "moment0" in FLAME, "TransVector" in TLM) calculation.
Therefore, the 7th column have to be reset to zero before calculate the envelope matrix
(which define as "state" in FLAME,  "ThetaMatrix" in TLM).

Here is the modification example https://github.com/kryv/FLAME/commit/3517d6602f39a951254b8cbace6cbceb8f0bb4d2 .

**Comment by shengb** [comment]
my understanding is that:
1. MpoleLevel = 0 for axisymmetric cavity model;
2. MpoleLevel = 1 for non-axisymmetric cavity model with Dipole component;
3. MpoleLevel = 2 for non-axisymmetric cavity model with Quad component; 

Do we support both Dipole & Quad component simultaneously?

Another question is that we do not have agreement to the machine precision for MpoleLevel != 0.
Need a solution

**Comment by kryv** [comment]
Sorry for not explaining enough.
In the main.cpp , MpoleLevel = 2 contains both dipole and quadrupole component.
(I think the comment-out document is unkind.)

I add the result after above bugfix modification https://github.com/kryv/FLAME/commit/3517d6602f39a951254b8cbace6cbceb8f0bb4d2 (this is same as the first comment)
The error order reached to the machine precision by the modification.
![ftrms3_mpole2](https://cloud.githubusercontent.com/assets/11188515/14656036/486f45da-0653-11e6-8062-5f0a5965cddf.png)

**Comment by shengb** [comment]
How about if I only want to include quad component then?
How about the MpoleLevel = 1? Do they agree to machine precision?

**Comment by kryv** [comment]
Renew about the MpoleLevel https://github.com/kryv/FLAME/commit/0d6ed50433cb7eb1aac218642c7fdc2bc3f5ca59 .
Now,
// Multipole level: 0 only include focusing and defocusing effects,
//                   1 include dipole terms,
//                   2 include quadrupole terms.
//                   3 include dipole and quadrupole terms.

and the comparison results are,

![rms_m1](https://cloud.githubusercontent.com/assets/11188515/14660809/77ef2028-0676-11e6-9232-b8a31220ee01.png)
