### ISSUE TITLE
main.cpp for a stripper implementation

### ISSUE THREAD

**Issue by kryv** [frib-high-level-controls/FLAME#5]
Now a stripper element works only for the longitudinal reference orbit calculation.

In the case of we implement a stripper for the transverse calculation, the number of charge states ("nChgState") increases after the stripper element, so it requires new "Machine" object inside the lattice element iteration.

In addition, "nChgState" loop is located outside the "ScaleandPropagate" for now. 
But in our model, every charge state beam go through the same lattice elements.
Therefore, there is no need to check the lattice elements for each charge state.

As a result I think we should move the "nChgState" loop into the element branch in the "ScaleandPropagete"  function. Is that possible ? 
I will appreciate your comment very much.

**Comment by jbengtsson** [comment]
Hi Kei,

Regarding #4.

Note that the Beam Envelope matrix (Sigma) for FLAME has zero in 7 row and
column. Hence, the orbit terms in M are not propagated by:

Sigma -> M Sigma M^T


However, they are propagated for the Orbit by (<x_vec>):

<x_vec> -> M <x_vec>


Please confirm,

Johan
