### ISSUE TITLE
Unit of "Bend angle"

### ISSUE THREAD

**Issue by kryv** [frib-high-level-controls/FLAME#6]
Now, the unit of bend angle is [rad] in the main source code and this wiki page:
http://frib-high-level-controls.github.io/FLAME/typesparams.html .

In the case of using [rad] as a input (e.g. from wiki page:),
elemname: sbend, L = 0.1, phi = 3.14159/16, K = 10; 
bend angle phi is written like this.

However, now the precision of the bend angle is only 6 digit.

I think we should define the unit of bend angle as [deg], and
multiply pi/180 inside the source code.
Because most bending magnets are defined by integer [deg],
we can keep the best precision easily by using pi value from the library.

**Comment by mdavidsaver** [comment]
> Now, the unit of bend angle is [rad] in the main source code and this wiki page:
> http://frib-high-level-controls.github.io/FLAME/typesparams.html .

I'll leave the question of units to @jbengtsson 

For my part, let it not be said that I'm insensitive to the precise needs of my scientific users.  With 254dad40b1bfb361d5732dfa6a6ffb9da6b24dc5 the parser now understands 'pi' as a numeric constant.  So the example mentioned becomes ```phi = pi/16```.  Have a nice weekend :)

**Comment by kryv** [comment]
I see about that.
Thank you!
