### ISSUE TITLE
Rename flame  executables

### ISSUE THREAD

**Issue by dylan171** [frib-high-level-controls/FLAME#7]
There is an executable in the tools directory called 'run_flame' and then in the vaccel directory called 'flame'.  It seems that run_flame is a general command line tool for executing a FLAME lattice, so I would prefer this to be called 'flame' and the other be called 'flameva' or 'flameioc' or something.

**Comment by mdavidsaver** [comment]
wrt. namespace, debian at least has no ```/usr/bin/flame```.  https://packages.debian.org/search?searchon=contents&keywords=flame

**Comment by mdavidsaver** [comment]
Addressed with c84fbaf1e3c33a54072e31e01762c51f6f366719 and 64386620159460e8ad3d1d60fae847468c9e4f45
